config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :toilets, only: [:index, :show] do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]

  # Naked Domain redirected to www
  # match "(*any)", to: redirect(subdomain: ""), via: :all, constraints: { subdomain: "www" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :toilet_features
  has_many :toilets, through: :toilet_features

  def icon
    case name
    when 'Gender Neutral'
      return "blue-uni.png"
    when 'Enclosed Stall'
      return "door.png"
    when 'Hand Dryer'
      return "hand-dryer.png"
    when 'Paper Towels'
      return "paper-towel.png"
    when 'Baby Changing'
      return "baby-boy.png"
    when 'Accessible'
      return "disability.png"
    when 'Private Sink'
      return "sink.png"
    when 'Spacious'
      return "spacious.png"
    when 'Mirror'
      return "mirror.png"
    when 'Sanitary Bin'
      return "bin.png"
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :toilet
  has_many :toilets

  validates :toilet_rating, presence: true
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :toilet_features
  has_many :features, through: :toilet_features

  validates :name, :address, :opens_at, :closes_at, :fee, :toilet_code, :rating, presence: true
  validates :fee, numericality: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def self.with_features(features)
    feature_amount = features.count
    toilet_ids = ToiletFeature.where(feature: features).map(&:toilet_id)
    # only select the toilets that have them multiple times
    uniq_toilet_ids = toilet_ids.select { |e| toilet_ids.count(e) == feature_amount }.uniq
    self.where(id: uniq_toilet_ids)
  end

  def avgratingrounded
    if reviews.pluck(:toilet_rating).present?
      avgrating = reviews.pluck(:toilet_rating).sum / reviews.pluck(:toilet_rating).count.to_f
      avgrating.round(1)
    else
      "No ratings yet"
    end
  end

  def ratings_category
    if avgratingrounded.is_a? Float
      if (avgratingrounded <= 5) && (avgratingrounded > 4.7)
        "Excellent"
      elsif (avgratingrounded <= 4.7) && (avgratingrounded > 4.5)
        "Very Good"
      elsif (avgratingrounded <= 4.5) && (avgratingrounded >= 4)
        "Good"
      else
        ""
      end
    end
  end

  def rating_html
    "⭐️ #{self.avgratingrounded} #{self.ratings_category} (#{self.reviews.count})"
  end

  def distance(latitude, longitude)
    @lewagon_coordinates = [51.532667, -0.076991]
    Geocoder::Calculations.distance_between(@lewagon_coordinates, [latitude, longitude], options = { units: :mi }).round(1)
  end
end

app/models/toilet_feature.rb
class ToiletFeature < ApplicationRecord
  belongs_to :toilet
  belongs_to :feature

  # has_many :features
  # has_many :toilets

  validates :toilet_id, uniqueness: { scope: :feature_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews

  validates :email, presence: true
  validates :email, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :redirect_root_domain

  private

  def redirect_root_domain
    if Rails.env.production?
      if request.host === "loosend.co"
        redirect_to "https://www.loosend.co#{request.fullpath}", status: 301
      end
    end
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:create]
  before_action :set_toilet, only: %i[new create]

  def create
    if user_signed_in?
      @review = Review.new(review_params)
      @review.toilet = @toilet
      @review.user = current_user
      # @markers = [
      #   {
      #     lat: @toilet.latitude,
      #     lng: @toilet.longitude,
      #     info_window: render_to_string(partial: "toilets/info_window", locals: { toilet: @toilet }),
      #     image_url: helpers.asset_url("toilet-paper.png")
      #   }
      # ]
      if @review.save
        respond_to do |format|
          format.json { render json: @review }
        end
        # redirect_to toilet_path(@toilet)
      else
        respond_to do |format|
          format.json { render json: { errors: true, message: "Please give a rating" } }
        end
      end
    else
      respond_to do |format|
        format.json { render json: { errors: true, message: "Please log in" } }
      end
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def set_toilet
    @toilet = Toilet.find(params[:toilet_id])
  end

  def review_params
    params.require(:review).permit(:toilet_rating, :comment)
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_toilet, only: [:show]

  def index
    @lewagon_coordinates = [51.532667, -0.076991]
    if params[:feature_ids].present?
      @features = Feature.where(id: params[:feature_ids])
      @toilets = Toilet.with_features(@features).near(@lewagon_coordinates, 20, :order => :distance)
    else
      @toilets = Toilet.near(@lewagon_coordinates, 20, :order => :distance)
    end
    @markers = @toilets.geocoded.map do |toilet|
      {
        lat: toilet.latitude,
        lng: toilet.longitude,
        info_window: render_to_string(partial: "info_window", locals: { toilet: toilet }),
        image_url: helpers.asset_url("toilet-paper.png")
      }
    end
  end

  def show
    @toilet = Toilet.find(params[:id])
    @review = Review.new
    @reviews = Review.where(toilet_id: params[:id]).order(updated_at: :desc)
    @markers = [
      {
        lat: @toilet.latitude,
        lng: @toilet.longitude,
        info_window: render_to_string(partial: "info_window", locals: { toilet: @toilet }),
        image_url: helpers.asset_url("toilet-paper.png")
      }
    ]
  end

  private

  def set_toilet
    @toilet = Toilet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loosend - The #1 And #2 App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titan+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@1,400;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap" rel="stylesheet">

    <%= favicon_link_tag asset_path('toilet-paper.png') %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="homepage">
    <h1 class="home-title">loo.send</h1>
    <h2 class="slogan">The #1 and #2 app</h2>
  </div>
  <div class="bigdiv">
  <div id="pin"> <img src="https://cdn-icons-png.flaticon.com/512/684/684908.png" alt="pin"></div>
      <div class='div-toilet' id='toilet-leg'></div>
      <div class='div-toilet' id='toilet-tank'></div>
      <div class='div-toilet' id='toilet-tank-lid'></div>
      <div class='div-toilet' id='flush-lever'></div>

      <div class='div-toilet' id='toilet-bowl'></div>
      <div class='div-toilet' id='toilet-lid'></div>
      <%= image_tag "watersplash.png", class: "waterimg" %>
      <div class='div-toilet' id='toilet-bowl-overlay'></div>
  </div>
  <div class="center">
    <a href="/toilets" class="home-button noHover">Find a toilet</a>
  </div>
</div>

app/views/reviews/_info_window.html.erb
<h2><%= link_to "#{toilet.name}", toilet_path(toilet) %></h2>
<p><%= toilet.address %></p>

app/views/reviews/create.js.erb
console.log('trigger modal!')

app/views/reviews/show.html.erb
<%= render "shared/navbar" %>
<div class="container pt-2">
  <h3><strong><%= "Thank you for your feedback, #{@review.user.first_name.capitalize}!" %></strong></h3>
  <ul class="list-group">
      <li class="list-group-item mt-1">
        <h5><%= "🕑 #{@review.user.first_name} on #{@review.created_at.strftime('%d %B %Y at %H:%M')}PM"%></h5>
        <h5>
          <%= "Rating: #{@review.toilet_rating} ⭐️" %>
        </h5>
        <p><%= "#{@review.comment}" %></p>
      </li>
  </ul>
  <%= link_to "Go back", toilet_path(@review.toilet) %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "loos navbar-brand" do %>
      loo.send
    <% end %>
      <div class=“navbar-nav me-auto”>
        <% if user_signed_in? %>
          <div class="nav-item active">
           <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "log-button" %>
          </div>
        <% else %>
          <div class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "log-button" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/toilets/_info_window.html.erb
<%= link_to toilet_path(toilet) do %>
<div>
  <h2 class="toilet-name"><%= "#{toilet.name}" %></h2>
  <% toilet.features.each do |feature| %>
    <%= image_tag "#{feature.icon}", id:"pop-feature"%>
  <% end %>
  <p>
    <%= "#{toilet.rating_html}" %>
    <br>
    <%= "#{toilet.distance(toilet.latitude, toilet.longitude)} miles away" %> <br>
  </p>
</div>
<% end %>

app/views/toilets/_toilet_info_window.html.erb
<h2><%= link_to "#{toilet.name}", toilet_path(toilet) %></h2>
<p><%= toilet.address %></p>

app/views/toilets/index.html.erb
<%= render "shared/navbar" %>

<div class="filters-box container d-flex justify-content-between">
  <div class="dropdown">
    <button class="filters-button dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Filter
    </button>
    <ul class="dropdown-menu">
          <%= form_with url: "/toilets", method: :get do |form| %>
            <% Feature.all.each do |feature| %>
                <li>
                  <%= check_box_tag 'feature_ids[]', feature.id -%>
                  <%= h feature.name -%>
                </li>
            <% end %>
            <%= form.submit "Apply Filters", class: "apply-filters btn btn-primary" %>
          <% end %>
          <button type="button" class="btn btn-secondary" id="see-all"><%= link_to "Clear Filters", toilets_path%></button>
    </ul>
  </div>
</div>

<% if @markers.empty? %>
  <div class="container">
    Sorry, we could not find a toilet that matched your search.
    Please try again.
  </div>
<% else %>
  <div class="container-map">
    <div style="width: 100%; height: 400px; margin: 0"
    data-controller="map"
    data-map-page-value="index"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
<% end %>

<div class="container-cards">
  <div class="row mt-2">
    <% if @features %>
      <h3 class="x-loos"><%= "#{@toilets.length} loos near you with #{@features.map(&:name).join(", ")}" %></h3>
    <% else %>
      <h3 class="x-loos"><%= "#{@toilets.length} loos near you" %></h3>
    <% end %>
    <% @toilets.first(14).each do |toilet| %>
    <div class="col-sm-12 mb-3" style="padding-left: 3px; padding-right: 3px">
      <%= link_to toilet_path(toilet), class: "card" do%>
        <div class="card-1">
          <p class="toilet-name"><%= toilet.name %><p>
        </div>
        <div class="card-2">
          <p class="right-side-description"><%= "#{toilet.rating_html}" %></p>
          <p class="right-side-description"><%=  "🕑 #{toilet.opens_at.strftime('%H:%M')}
          - #{toilet.closes_at.strftime('%H:%M')}" %>
          <p class="right-side-description">
            <%= "#{toilet.distance(toilet.latitude, toilet.longitude)} miles away" %>
          <p>
          </p>
        </div>
      <% end %>
    </div>
        <hr class="dotted">
    <% end %>
  </div>
</div>

app/views/toilets/show.html.erb
<%= render "shared/navbar" %>
<% content_for :meta_title, "#{@toilet.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @toilet.address %>
<% content_for :meta_image %>

<div class="map-showpage" style="width: 100%; height: 400px;"
  data-controller="map"
  data-map-page-value="show"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>


<div class="container-bcg">
  <div class="d-flex justify-content-between">
    <h3 class="toilet-title-show"><%= "#{@toilet.name}" %></h3>
    <div id="gmap-btn">
      <a class="btn directions-button" href="<%="https://www.google.com/maps/dir/?api=1&destination=#{@toilet.address}"%>" target="_blank" role="button">Directions</a>
    </div>
  </div>
  <h5 class="address"><strong><%= "#{@toilet.address} | #{@toilet.rating_html}" %></strong></h5>
  <div class="icons-card row row-cols-1 row-cols-md-4 g-4 d-flex justify-content-center mt-3">
    <% @toilet.features.each do |feature| %>
      <div class="col-lg-4 col-md-4 col-sm-4 col-4">
        <div class="d-flex flex-column">
          <div class="icon-div">
            <%= image_tag "#{feature.icon}", class:"feature"%>
          </div>
          <div class="feature-name p-2">
            <%= feature.name %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="div-for-filipe">
  <%# <h5><%= "Leave a review for #{@toilet.name}"</h5> %>
  <%= simple_form_for [@toilet, @review], data: { controller: "review-modal", review_modal_target: "form", action: "submit->review-modal#submit" } do |f| %>
    <div data-review-modal-target="rating" class="red-text"></div>
    <%= f.input :toilet_rating, required: false, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating" } } %>
    <%= f.input :comment, label: "Leave a comment (optional)"  %>
    <%= f.submit "Submit your review", id: "confirm", class: "button-reviews btn btn-primary" %>
  <% end %>
  <!-- Modal -->
  <% if user_signed_in? && @review.errors.messages.empty? %>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="toilet-title-show" id="exampleModalLabel"><%= "#{@toilet.name}" %></h3>
          </div>
          <div class="modal-body">
            <%= "Thank you for leaving a review, #{current_user.first_name.capitalize}!"%>
          </div>
          <div class="modal-footer">
            <%= link_to "Close", toilet_path(@toilet), class: "btn btn-secondary", id: "see-all" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <%# <%= link_to "- Back to All Toilets -", toilets_path %>
  </div>

  <h5 class="all-reviews mt-3"><%= "all reviews" %></h5>
  <ul class="list-group">
    <% @reviews.each do |review| %>
      <% if review.comment.present? %>
        <li class="reviews-cards list-group-item mt-3">
        <strong><%="#{review.user.first_name} on #{review.created_at.strftime("%A, %b %d, %Y")}" %></strong>
        <br>
          <strong><%= '⭐' * review.toilet_rating %></strong>
          <p><%= "#{review.comment}" %></p>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>